"""Add field_validations and remarks to ParsedReport

Revision ID: cf5556774762
Revises: 70af18a757a1
Create Date: 2026-07-16 22:26:20.254315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5556774762'
down_revision: Union[str, Sequence[str], None] = '70af18a757a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_reports', sa.Column('field_validations', sa.JSON(), nullable=True))
    op.add_column('parsed_reports', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_reports', 'remarks')
    op.drop_column('parsed_reports', 'field_validations')
    # ### end Alembic commands ###
