from io import BytesIO

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.user import User
from app.services.export_service import generate_csv, generate_excel, generate_pdf
from app.services.report_service import get_approved_report, get_report, list_reports, serialize_report
from app.utils.audit import log_action

router = APIRouter()


@router.get("/")
def reports_list(page: int = Query(1, ge=1), page_size: int = Query(10, ge=1, le=100), current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    total, items = list_reports(db, current_user, page, page_size)
    return {"total": total, "page": page, "page_size": page_size, "items": items}


def _export(report_id, export_format, generator, media_type, extension, current_user, db):
    report = get_approved_report(db, report_id, current_user)
    content = generator(report)
    log_action(db, report.document_id, "Report Generated", "Success", f"{export_format.upper()} report generated by {current_user.email}")
    filename = f"report_{report.id}.{extension}"
    return StreamingResponse(BytesIO(content), media_type=media_type, headers={"Content-Disposition": f'attachment; filename="{filename}"'})


@router.get("/export/pdf/{report_id}")
def export_pdf(report_id: int, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    return _export(report_id, "pdf", generate_pdf, "application/pdf", "pdf", current_user, db)


@router.get("/export/excel/{report_id}")
def export_excel(report_id: int, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    return _export(report_id, "excel", generate_excel, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx", current_user, db)


@router.get("/export/csv/{report_id}")
def export_csv(report_id: int, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    return _export(report_id, "csv", generate_csv, "text/csv; charset=utf-8", "csv", current_user, db)


@router.get("/{report_id}")
def report_detail(report_id: int, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    return serialize_report(get_report(db, report_id, current_user))
